[package]
name = "fltk-plot"
version = "0.2.0"
authors = ["Oguz Meteer <info@guztech.nl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "^1.3", features = ["fltk-bundled"] }
